### ISSUE TITLE
Just for documentation of changes (development)

### ISSUE THREAD

**Issue by juliankoehn** [knkcms/charts#3]
Changed in `cms-solutions/values.yaml`

```yaml
frontend:
  image:
    repository: knkcms.azurecr.io/cms-frontend-dev
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "b93e4d3"
```

**to**
```yaml
frontend:
  image:
    repository: knkcms.azurecr.io/cms-frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "d7c55af"
```

Repository from -dev to cms-frontend, tag version to manually tagged version.
